name: Create Sophia Version File
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create/update text file
      run: echo "This is my test" > test-auto.txt
    - name: Commit and Push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # use account 'github-actions[bot]' to set the git config
        git checkout -b example-patches
        git add -A
        git commit -m "commit message"
        git push origin example-patches
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        base: master
        branch: example-patches