name: Create Sophia Version File
on:
  release:
    types: [ created ]


jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Create file
        run: |
          printf "Hello\nWorld\n" > ~/hw.txt
