name: Create Sophia Version File
on:
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create/update text file
        run: echo "var=x" > test.txt
        # If 'test.txt' is existing, overwrite its text with "var=x"
        # If 'test.txt' doesn't exist, automatically create it and write the text "var=x"