name: Create Sophia Version File Manual
on:
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create/update text file
      run: echo "var=x" > test.txt