name: Create Sophia Version File
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create/update text file
      run: echo "tag created again" > test-auto.txt
    - name: Commit and Push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # use account 'github-actions[bot]' to set the git config

        git add -A
        git commit -m "commit message"
        git fetch origin master
        git push origin HEAD:master